name: Build ByneGram APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Make gradlew executable
      run: chmod +x ./gradlew
      
    - name: Build Release APK
      run: |
        ./gradlew assembleRelease --no-daemon --stacktrace
        
    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ByneGram-APK
        path: app/build/outputs/apk/release/*.apk
        retention-days: 30
